### ISSUE TITLE
修正要望・再検討事項一覧（対応期限：11月末）

### ISSUE THREAD

**Issue by mihye1128** [nino-plus/deer20201105#75]
## 修正依頼
- [ ] firestore.rules：ルールを設定 #76   @mihye1128 
- [x] 一覧画面：SPレイアウトの時、ログインがクリックできない問題解決 #77  @mihye1128 
- [x] フォーム画面：下書き・公開ボタンのテキスト編集 #78 @mihye1128

- [ ] ホーム画面：ファンが回る問題解決 #79  @kkkkoki  @mihye1128 
- [x] ホーム画面：サインボードにCAMPへのリンクを追加 #80   @kkkkoki

- [ ] ホーム画面：一覧画面へのリンクボタンの表示切替実装 #81   @hide-a1 
- [ ] ホーム画面：タイムラインの自動表示切替をfalseにする #82  @hide-a1 

- [ ] ホーム画面：タイムラインのメッセージ開封時にユーザー名表示 #83  @yusukegunji
- [ ] ホーム画面：「トップへ戻る」ボタンを常に表示（全てのカードを閉じる） #84  @yusukegunji

## 対応期限
11月末まで
